### ISSUE TITLE
[C++] Incorrect text syntax color on generated image

### ISSUE THREAD

**Issue by AndhikaWB** [kufii/CodeSnap#13]
VS Code v1.39.2
CodeSnap v1.0.15

![aaaa](https://user-images.githubusercontent.com/17119394/67160836-044c0d80-f37f-11e9-8c26-2c7e84c67add.PNG)

As you can see, only variable `angka` is colored as light blue. Other variables such as `kol`, `bar`, `baris`, `kolom`, etc. are colored as white on the generated image. `cout` and `cin` are also colored as white.

Original code: https://pastebin.com/tuLaWuEP

Simple C++ code (without 2D array) works fine, no color issue so far.

**Comment by kufii** [comment]
Thanks for the report,

What theme are you using? is this the default c++ language definition?

I thought it was default theme, but when I select the default theme, the colors match your generated image even in my editor.

**Comment by AndhikaWB** [comment]
I'm using the default dark theme on Windows. Yes, I didn't use any custom definition (I don't even know how to declare it yet). I also installed Polacode after this weird bug, seems to be affected as well. Did you try using my code?

After trying today, simple codes are now affected by this bug as well:
![Screenshot_2](https://user-images.githubusercontent.com/17119394/67250301-056f5e80-f495-11e9-9dae-2e93e4b8cb42.png)

My `settings.json` file doesn't even have any modification related to theme: https://pastebin.com/DKeKVzhr

I'm using MinGW C++ compiler with C/C++ extensions installed if that helps, I will try cleaning my extensions folder or even deleting the entire data folder to see if the bug still exist.

**Comment by AndhikaWB** [comment]
Issue still persist even after resetting my VS Code data (I deleted the `user-data` folder and `extensions\adpyke.codesnap-1.0.15` folder manually).

My list of installed extensions:
![Screenshot_3](https://user-images.githubusercontent.com/17119394/67250885-5a13d900-f497-11e9-97bc-ecebb929c735.png)

**Comment by kufii** [comment]
What's interesting is that when using the default vs code settings my token colors are slightly different. Even when using your cpp file. Variables are white not blue like yours, and look the same in CodeSnap. I'll investigate further when I have some free time

**Comment by AndhikaWB** [comment]
Maybe you don't have any C++ compiler installed or don't have C/C++ extensions installed?

**Comment by kufii** [comment]
What OS are you on? Looks like Windows 10 but just want to be sure

**Comment by kufii** [comment]
I don't have the c++ compiler but I do have the extensions. I'll install the compiler when I'm at my pc later

**Comment by AndhikaWB** [comment]
Yes, Windows 10 but LTSC edition. Doesn't make any difference to Windows 10 Pro/Home in this case.

**Comment by AndhikaWB** [comment]
In case you don't want to install C++ compiler (because you don't need it anyway), you can just use [Nuwen's MinGW distro](https://nuwen.net/mingw.html).

Extract it somewhere like `C:\MinGW`. Open Command Prompt, type `set "PATH=%PATH%;C:\MinGW\bin"` (where `gcc.exe` exist) and then type `YourVSCodePath\Code.exe` to run VS Code.

MinGW will now be recognized by VS Code without the need of installing it. Just delete `C:\MinGW` later.

**Comment by kufii** [comment]
I'm now successfully reproducing the issue.

The colors are being changed by `C_Cpp.enhancedColorization`. Unfortunately I have not yet found a way to get colors set by extensions, only ones set by themes.

**Comment by kufii** [comment]
If you want to disable this feature, (I personally don't see the point of it?), you could do `C_Cpp.enhancedColorization: "Disabled"`. I will continue to look into a way to fix it though

**Comment by AndhikaWB** [comment]
I'm fine with it actually, no need to push yourself. I'll try to make a request (or search for the same issue) on Polacode repo and see if it can get fixed, or maybe on VS Code repo itself.

**Comment by amir1376irani** [comment]
I'm using an extension named Better Comments which install counts are about a million user.
it makes comments colorful. For example if you type `//! my comment` as a new comment line, it gets red.
Unfortunately CodeSnap shows all of those comments in default green color, not what is really shown on screen.

Better Comments link for vs-code : https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments
