### ISSUE TITLE
Weird formatting after taking shot

### ISSUE THREAD

**Issue by edevars** [kufii/CodeSnap#21]
Hi, im tried to take shots with codesnap because polacode did me a bad formating while I took a shot, but occurs the same error.

**This is before I took the shot**

![Screenshot at 2019-12-04 19-30-16](https://user-images.githubusercontent.com/39858532/70195889-9e1c0f80-16cc-11ea-9c03-41a027b750ef.png)

**This is the result of the shot**
![code](https://user-images.githubusercontent.com/39858532/70195966-cdcb1780-16cc-11ea-92b9-14285748d5a0.png)

This is the info of my vscode 

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.12-200.fc30.x86_64

My SO is fedora 30

![Screenshot at 2019-12-04 19-39-22](https://user-images.githubusercontent.com/39858532/70196267-d07a3c80-16cd-11ea-88b5-d7fd2a8df0b4.png)

I think this is a better extension than polacode, luck in solving this bug.

**Comment by kufii** [comment]
can you post your current settings.json?

**Comment by kufii** [comment]
Actually, can you try using the latest version of codesnap? I have a feeling this is because the published version of dom-to-image-more is pretty out of date. I've manually included the latest version in this commit: https://github.com/kufii/CodeSnap/commit/470649b3c33043bd7fea419457226d1d8b5e6184
