### ISSUE TITLE
macos

### ISSUE THREAD

**Issue by JackFlyL** [kufii/CodeSnap#23]
CodeSnap: /bin/sh: ./scripts/osx-copy-image: Permission denied

**Comment by kufii** [comment]
hmm... I'll look into fixing the permissions, but in the meantime, try running `chmod +x` on the `osx-copy-image` file, and it should work fine

**Comment by kufii** [comment]
Actually, can you please update to the latest version and let me know if the issue still occurs?

**Comment by hzzhoudian** [comment]
![image](https://user-images.githubusercontent.com/42569422/71442861-b5d23b00-2742-11ea-8f9a-39adab7f7906.png)
![image](https://user-images.githubusercontent.com/42569422/71442876-cbdffb80-2742-11ea-9d65-a1dfcd33d7a4.png)

**Comment by jenky** [comment]
Still having this issue

**Comment by zavoluk** [comment]
Same here

**Comment by kufii** [comment]
please update, the issue appears to be fixed now.
