### ISSUE TITLE
No color rendered

### ISSUE THREAD

**Issue by MisLink** [kufii/CodeSnap#24]
environment: MacOS 10.14.6

<img width="1292" alt="图片" src="https://user-images.githubusercontent.com/8280169/71613432-6af07180-2be1-11ea-9ac6-bc41df5c4f8c.png">

I tried to disable all extensions except CodeSnap but no luck.

**Comment by kufii** [comment]
what version of VS code are you using?

**Comment by MisLink** [comment]
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by ricealexander** [comment]
I'm getting this same issue on my Windows machine

![codesnap-ignore-syntax-highlighting](https://user-images.githubusercontent.com/18580400/73990737-b51af000-490f-11ea-9630-e04196e79189.png)

```
Microsoft Windows 10 Education
10.0.17763 Build 17763
```

**VSCode > Help > About**
```
Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763
```

**settings.json**
```
  "codesnap.boxShadow": "none",
  "codesnap.containerPadding": "0",
  "codesnap.roundedCorners": false,
  "codesnap.showLineNumbers": true,
  "codesnap.showWindowControls": false,
  "codesnap.showWindowTitle": false,
  "codesnap.target": "container",
  "codesnap.transparentBackground": true,
```

**Comment by kufii** [comment]
Do you happen to have `editor.copyWithSyntaxHighlighting` set to false? This extension relies on this copy behaviour so it won't work with it set to true

**Comment by ricealexander** [comment]
I do have `editor.copyWithSyntaxHighlighting` set to false. This makes sense.

**Comment by MisLink** [comment]
Yes, I set `editor.copyWithSyntaxHighlighting` to false, changing it to true resolve this issue.

**Comment by Kannnnng** [comment]
I think this information should be written in the README.txt, it will be useful for some people.

**Comment by kufii** [comment]
I didn't even realize that was a VS Code setting, thanks for letting me know! I'll add it to the readme

**Comment by kufii** [comment]
Yes you're totally right, I'll add it to the readme
