### ISSUE TITLE
Unescaping code

### ISSUE THREAD

**Issue by Falci** [kufii/CodeSnap#32]
I tried to make a screenshot of a code, and the resulting image is slight different.

The minimum example is this: Take a CodeSnap of this: `'%40'`. The result is:
![image](https://user-images.githubusercontent.com/1330573/82305522-067e5500-99be-11ea-8eb9-c0f7b856df52.png)

Is there an option where I can disable this replace?

**Comment by kufii** [comment]
I'm unable to reproduce this issue. Which OS and VS Code version are you on?

**Comment by Falci** [comment]
I'm not able to reproduce it anymore.
