### ISSUE TITLE
Add Extension to Open VSX Marketplace

### ISSUE THREAD

**Issue by GulajavaMinistudio** [kufii/CodeSnap#34]
VS Codium and other VS Code Fork (Code OSS and Eclipse Theia) now use Open VSX Registry instead VS Code Marketplace. 
[https://open-vsx.org/](https://open-vsx.org/) .
[https://github.com/VSCodium/vscodium/blob/master/DOCS.md](https://github.com/VSCodium/vscodium/blob/master/DOCS.md)

Open VSX is open source marketplace for VS Code fork that made by Eclipse Foundation.
[https://www.gitpod.io/blog/open-vsx/](https://www.gitpod.io/blog/open-vsx/)

And i checking your Codesnap extension is still not available in this open marketplace extension. You can read this easy guide, how to publish your extension to Open VSX Marketplace. 
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by kufii** [comment]
https://open-vsx.org/extension/adpyke/codesnap published!
