### ISSUE TITLE
Support for "Better Comments" VSCode extension compatibility

### ISSUE THREAD

**Issue by sajadko** [kufii/CodeSnap#36]
Hi , i use this for colorize comments :
https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments

please add support for this extension.
thank you.

**Comment by kufii** [comment]
unfortunately with the way this extension works, getting the colours just isn't possible

**Comment by sathya9897** [comment]
that's really unfortunate but can you implement the same comments highlight following exactly `better comments` standards. is it possible? it would be really great if that feature would be available in this extension. Thanks for this extension and your work. it's really helpful to share some code with beauty.
