### ISSUE TITLE
Wondering if this can be made to copy from integrated terminal...

### ISSUE THREAD

**Issue by studoot** [kufii/CodeSnap#38]
Loving your extension - it's come in very useful for me with presentations & documentation.

I was wondering whether it would be possible to use Codesnap on text selected in the integrated terminal, as I presume that has a similar structure to an editor window - that would let me get the same level of fidelity with command-lines & their related output as I can get for my code...

**Comment by kufii** [comment]
it's a good idea, but it doesn't look like we're able to extract the colours from the terminal, so unfortunately it doesn't seem possible.
