### ISSUE TITLE
Transparent background not working when saving to clipboard

### ISSUE THREAD

**Issue by wenfangdu** [kufii/CodeSnap#39]
Settings
```json
  "codesnap.boxShadow": "none",
  "codesnap.showLineNumbers": false,
  "codesnap.showWindowControls": false,
  "codesnap.transparentBackground": true,
```
Save to clipboard

![image](https://user-images.githubusercontent.com/28700378/88495870-e25a7800-cfed-11ea-9f93-cb108d571a21.png)

Save to disk

![code 2](https://user-images.githubusercontent.com/28700378/88495888-f00ffd80-cfed-11ea-8a3e-bb5259b90520.png)

**Comment by kufii** [comment]
which OS are you using?

**Comment by wenfangdu** [comment]
Windows 10

**Comment by AndhikaWB** [comment]
Can confirm also on Windows 10 LTSC (v1809).

**Comment by rdhar** [comment]
Can also confirm the same on Windows 10 Pro v2004 (notice the grey background behind the rounded corners).

**Copied to clipboard**
![image](https://user-images.githubusercontent.com/19497993/93672395-6ab34180-faa2-11ea-9796-9fb61c6af371.png)

**Saved to disk**
![codesnap disk](https://user-images.githubusercontent.com/19497993/93672416-97ffef80-faa2-11ea-8576-3e5b9903008e.png)

Configuration:
```json
"codesnap.boxShadow": "none",
"codesnap.containerPadding": "0",
"codesnap.showLineNumbers": false,
"codesnap.showWindowControls": false,
"codesnap.transparentBackground": true
```

**Comment by wenfangdu** [comment]
The current implementation [copy-image.ps1](https://github.com/kufii/img-clipboard/blob/master/scripts/copy-image.ps1) can't copy transparent background, [file2clip](https://github.com/rostok/file2clip) can.

**Comment by wenfangdu** [comment]
After being terribly screwed by PowerShell, I made PR https://github.com/kufii/img-clipboard/pull/7.

**Comment by rdhar** [comment]
This is terrific, nice work @wenfangdu!

**Comment by Curious-And-Patient** [comment]
Issue is still present - any tip on how to solve it? (or maybe I am doing something wrong)

**Comment by wenfangdu** [comment]
@Curious-And-Patient Looks like a VSCode issue, it was working before.

**Comment by wenfangdu** [comment]
@Curious-And-Patient I just tested it, it works on VSCode v1.69.2.

**Comment by wenfangdu** [comment]
@Curious-And-Patient I just tested it, it works on VSCode v1.69.2.

**Comment by FDiskas** [comment]
Did not work again
Mac OS
```json
{
    "codesnap.realLineNumbers": true,
    "codesnap.showWindowTitle": true,
    "codesnap.shutterAction": "copy",
    "codesnap.transparentBackground": true,
    "codesnap.backgroundColor": "transparent",
    "codesnap.boxShadow": "rgba(0, 0, 0, 0.55) 0px 10px 38px"
}
```

**Comment by ndabAP** [comment]
I can confirm on Linux that transparent background doesn't work in the latest version.
