### ISSUE TITLE
Does not work under OSX

### ISSUE THREAD

**Issue by pyrsmk** [kufii/CodeSnap#40]
When running on Mac, the command seems to do nothing. No error notification and there's no error in the dev tools too.

Worth noting that I'm using the Settings Sync extension to sync my settings/extensions across my Mac/Linux environments. The CodeSnap extension has been installed under Linux first (and everything worked well) then it has been synced to my Mac environment.

VSCode version: 1.47.3
OSX version: Catalina 10.15.4

<img width="1354" alt="Capture d’écran 2020-07-31 à 14 49 08" src="https://user-images.githubusercontent.com/214497/89036838-b9afe680-d33d-11ea-88c9-10ab81314817.png">

**Comment by pyrsmk** [comment]
I just realized this was not working: I didn't select the code to snap.

So, instead of a bug report, this issue is in fact a feature request: please add some message to instruct the user to select some code if he has not ;)

**Comment by kufii** [comment]
this is a good UX comment! thank you
