### ISSUE TITLE
Does not preserve indentation

### ISSUE THREAD

**Issue by d4rk-d4nph3** [kufii/CodeSnap#43]
## Version
VScode version: 1.48.0 (Stable)
CodeSnap Version: 1.0.27

CodeSnap is not preserving indentation in my python code.

## Original Code
![image](https://user-images.githubusercontent.com/61026070/90372539-4540ab80-e090-11ea-9617-f346a6d96fae.png)

## CodeSnap Output
![image](https://user-images.githubusercontent.com/61026070/90372567-4eca1380-e090-11ea-942d-f4b1a9ca4a06.png)

**Comment by NatoBoram** [comment]
Make CodeSnap's editor larger, it'll change the size of the screenshot
