### ISSUE TITLE
Automatically Copy Photo to Clipboard

### ISSUE THREAD

**Issue by evannilaz** [kufii/CodeSnap#51]
Just like screenshot system on other applications, I think it would be good to copy the screenshot of code to clipboard, and ask user whether to save it or not. Is this possible?

**Comment by AndhikaWB** [comment]
You can just press CTRL + C to copy it to your clipboard (there is currently no button). Auto copy would be hard and unecessary, I mean how do CodeSnap know when to copy? Even if it was preconfigured to copy every X seconds it would be an overkill for a simple use.

**Comment by evannilaz** [comment]
No, I mean to copy the image *all* the time, and then ask user whether to save it in user's PC.
And I think it might not be too hard (if there's a security issue, then not) to do 'cause you can just copy sth into user's clipboard by JS.

**Comment by AndhikaWB** [comment]
Uh, I think you misunderstood me before. You can copy the image directly from CodeSnap (without saving it first) by pressing CTRL + C. When the image blink then it's already copied to clipboard. I don't really get what you mean with "copy the image all the time", but pressing CTRL + C is not that hard.

**Comment by evannilaz** [comment]
Well, you're sort of right.

**Comment by Akronae** [comment]
well, for my use case it would be great if the image could just be automatically copied to the clipboard when I run the command and dont disturb the layout with a new editor tab
