### ISSUE TITLE
Option to split to bottom instead of side

### ISSUE THREAD

**Issue by bbugh** [kufii/CodeSnap#52]
This is a great tool, thank you!

Unfortunately, every time I use it, I have to move the split pane to the bottom instead of the right. I have a small screen laptop, and it results in my code having to fit in 40 line length characters. It seems like it would make more sense to split to the bottom so the screenshot actually looks like the code rather than being squished, and/or adding an option to do this. 

What do you think?

Current behavior:

![code](https://user-images.githubusercontent.com/438465/96371544-cddad700-1127-11eb-9125-0d800f9b9ca1.png)

Ideal behavior:

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/438465/96371588-f19e1d00-1127-11eb-9c0d-c7ad01faa514.png">

**Comment by Lxstr** [comment]
#63 Should mean this is done now?

**Comment by bbugh** [comment]
Hurray!! Thanks @Lxstr!
