### ISSUE TITLE
damn this just sucks and copycat of code snapshot

### ISSUE THREAD

**Issue by abdullzz** [kufii/CodeSnap#60]
simply not working

**Comment by kufii** [comment]
I made this because the alternatives were buggy and were missing features that I considered important. Thanks for the feedback, maybe don't be a dickhead to random devs maintaining open source projects in the future

**Comment by abdullzz** [comment]
its not even working. not just buggy

**Comment by kufii** [comment]
Works for me and most people considering the positive feedback it's received, seems like a you issue. If you're more specific about what's not working instead of just being a dick maybe I'd be able to help resolve it

**Comment by abdullzz** [comment]
the similar problem from its original source. it cannot handle 1000 rows. if it's just a couple of lines why would I need an extension for it?. that's what makes me a dickhead. I thought this was another "extension" from that troubling one

**Comment by kufii** [comment]
This project leverages dom-to-image to convert to an image. The issue with handling extremely large doms is with that project and not codesnap so feel free to take it up with them. The purpose of this project is to take smaller snippets with nice formatting, not massive full documents. You probably shouldn't be storing full files in an image anyways, it's pretty inefficient
