### ISSUE TITLE
Image only  contains half of selected code

### ISSUE THREAD

**Issue by frankhale** [kufii/CodeSnap#61]
Selected 600 lines of code and image only contains 300 lines of that with the rest empty. Image looks like it would contain the 600 lines but only half shows, the other half is empty.

**Comment by frankhale** [comment]
I've tried several of these code snapshot extensions and all are the same. You guys copying and pasting from one another???

**Comment by frankhale** [comment]
Might be a bug in API to take screenshots in VSCode since several other extensions like this do the same thing

**Comment by duckimann** [comment]
I don't know why you want to take a screenshot of 600 lines of code BUT as far i can tell, there is something wrong with the library they're using which is "dom-to-image-even-more".

![image](https://user-images.githubusercontent.com/46382253/135734961-6320933c-ccb2-45e0-8eb2-61c837d2a97c.png)

i got the base64 from the generated image and load it to a photo viewer and it's only have the half of the image.

**Comment by duckimann** [comment]
I just try to change the SNAP_SCALE to 1 and it captured 800 lines perfectly but at the original scale (it was x2 by default)
