### ISSUE TITLE
CodeSnap Don't run

### ISSUE THREAD

**Issue by edarblanco** [kufii/CodeSnap#62]
Select a piece of code, and I run codesnap and it gives me an error like this
**The command "CodeSnap 📸" resulted in an error (command 'codesnap.start' not found)**
and it doesn't run at all, remove, reinstall, erase settings completely in vscode and nothing worked, I always get the same error

**Comment by edarblanco** [comment]
Fix, on version 1.3.2

**Comment by Karan0-dangol** [comment]
i just connected my github with vs then it started this problem. didn't fix with reinstall
