### ISSUE TITLE
Images are getting cut off on 1.3.0

### ISSUE THREAD

**Issue by MrThePlague** [kufii/CodeSnap#64]
Hello!

Since updating to `1.3.0` it looks as though images are getting cut off. Downgrading to `1.2.1` seems to resolve the issue.

`1.2.1`

![121](https://user-images.githubusercontent.com/6709366/114940519-2cdf8700-9dff-11eb-9784-1e4f3cc332fb.png)

`1.3.0`

![130](https://user-images.githubusercontent.com/6709366/114940537-34069500-9dff-11eb-8e95-2499bccee6fb.png)

## Troubleshooting

So far I've tried:

* Restarting VS Code
* Re-installing the extension
* Two different machines (Intel Mac, Apple Silicon Mac)

**Comment by TheDutchCoder** [comment]
I can confirm the same issue:
![image](https://user-images.githubusercontent.com/1668207/115032011-d32a9b80-9e96-11eb-9800-0f2475edb6c8.png)

**Comment by kufii** [comment]
Thanks for the report, I'll fix asap

**Comment by kufii** [comment]
Fixed in 1.3.1

**Comment by MrThePlague** [comment]
Thanks!!
